export const issuesMock = [
  {
    url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/37',
    repository_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project',
    labels_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/37/labels{/name}',
    comments_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/37/comments',
    events_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/37/events',
    html_url: 'https://github.com/ShareCastG52/Q2_Project/pull/37',
    id: 246871247,
    number: 37,
    title: 'disregard #2 ',
    user: {
      login: 'Gwillison415',
      id: 22106099,
      avatar_url: 'https://avatars2.githubusercontent.com/u/22106099?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Gwillison415',
      html_url: 'https://github.com/Gwillison415',
      followers_url: 'https://api.github.com/users/Gwillison415/followers',
      following_url: 'https://api.github.com/users/Gwillison415/following{/other_user}',
      gists_url: 'https://api.github.com/users/Gwillison415/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Gwillison415/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Gwillison415/subscriptions',
      organizations_url: 'https://api.github.com/users/Gwillison415/orgs',
      repos_url: 'https://api.github.com/users/Gwillison415/repos',
      events_url: 'https://api.github.com/users/Gwillison415/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Gwillison415/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2017-07-31T20:17:36Z',
    updated_at: '2017-07-31T20:17:36Z',
    closed_at: null,
    pull_request: {
      url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/pulls/37',
      html_url: 'https://github.com/ShareCastG52/Q2_Project/pull/37',
      diff_url: 'https://github.com/ShareCastG52/Q2_Project/pull/37.diff',
      patch_url: 'https://github.com/ShareCastG52/Q2_Project/pull/37.patch',
    },
    body: 'org master to gw dev',
  },
  {
    url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/36',
    repository_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project',
    labels_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/36/labels{/name}',
    comments_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/36/comments',
    events_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/36/events',
    html_url: 'https://github.com/ShareCastG52/Q2_Project/pull/36',
    id: 246869449,
    number: 36,
    title: 'disregard this PR',
    user: {
      login: 'Gwillison415',
      id: 22106099,
      avatar_url: 'https://avatars2.githubusercontent.com/u/22106099?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Gwillison415',
      html_url: 'https://github.com/Gwillison415',
      followers_url: 'https://api.github.com/users/Gwillison415/followers',
      following_url: 'https://api.github.com/users/Gwillison415/following{/other_user}',
      gists_url: 'https://api.github.com/users/Gwillison415/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Gwillison415/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Gwillison415/subscriptions',
      organizations_url: 'https://api.github.com/users/Gwillison415/orgs',
      repos_url: 'https://api.github.com/users/Gwillison415/repos',
      events_url: 'https://api.github.com/users/Gwillison415/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Gwillison415/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2017-07-31T20:11:06Z',
    updated_at: '2017-07-31T20:11:06Z',
    closed_at: null,
    pull_request: {
      url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/pulls/36',
      html_url: 'https://github.com/ShareCastG52/Q2_Project/pull/36',
      diff_url: 'https://github.com/ShareCastG52/Q2_Project/pull/36.diff',
      patch_url: 'https://github.com/ShareCastG52/Q2_Project/pull/36.patch',
    },
    body: 'using this for github API research',
  },
  {
    url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/17',
    repository_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project',
    labels_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/17/labels{/name}',
    comments_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/17/comments',
    events_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/17/events',
    html_url: 'https://github.com/ShareCastG52/Q2_Project/issues/17',
    id: 238924244,
    number: 17,
    title: 'login DELETE route',
    user: {
      login: 'meghanprestemon',
      id: 24230076,
      avatar_url: 'https://avatars1.githubusercontent.com/u/24230076?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/meghanprestemon',
      html_url: 'https://github.com/meghanprestemon',
      followers_url: 'https://api.github.com/users/meghanprestemon/followers',
      following_url: 'https://api.github.com/users/meghanprestemon/following{/other_user}',
      gists_url: 'https://api.github.com/users/meghanprestemon/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/meghanprestemon/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/meghanprestemon/subscriptions',
      organizations_url: 'https://api.github.com/users/meghanprestemon/orgs',
      repos_url: 'https://api.github.com/users/meghanprestemon/repos',
      events_url: 'https://api.github.com/users/meghanprestemon/events{/privacy}',
      received_events_url: 'https://api.github.com/users/meghanprestemon/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 632975275,
        url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/labels/bug',
        name: 'bug',
        color: 'ee0701',
        default: true,
      },
      {
        id: 632975280,
        url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/labels/question',
        name: 'question',
        color: 'cc317c',
        default: true,
      },
      {
        id: 632975281,
        url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/labels/wontfix',
        name: 'wontfix',
        color: 'ffffff',
        default: true,
      },
    ],
    state: 'open',
    locked: false,
    assignee: {
      login: 'Gwillison415',
      id: 22106099,
      avatar_url: 'https://avatars2.githubusercontent.com/u/22106099?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Gwillison415',
      html_url: 'https://github.com/Gwillison415',
      followers_url: 'https://api.github.com/users/Gwillison415/followers',
      following_url: 'https://api.github.com/users/Gwillison415/following{/other_user}',
      gists_url: 'https://api.github.com/users/Gwillison415/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Gwillison415/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Gwillison415/subscriptions',
      organizations_url: 'https://api.github.com/users/Gwillison415/orgs',
      repos_url: 'https://api.github.com/users/Gwillison415/repos',
      events_url: 'https://api.github.com/users/Gwillison415/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Gwillison415/received_events',
      type: 'User',
      site_admin: false,
    },
    assignees: [
      {
        login: 'Gwillison415',
        id: 22106099,
        avatar_url: 'https://avatars2.githubusercontent.com/u/22106099?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/Gwillison415',
        html_url: 'https://github.com/Gwillison415',
        followers_url: 'https://api.github.com/users/Gwillison415/followers',
        following_url: 'https://api.github.com/users/Gwillison415/following{/other_user}',
        gists_url: 'https://api.github.com/users/Gwillison415/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/Gwillison415/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/Gwillison415/subscriptions',
        organizations_url: 'https://api.github.com/users/Gwillison415/orgs',
        repos_url: 'https://api.github.com/users/Gwillison415/repos',
        events_url: 'https://api.github.com/users/Gwillison415/events{/privacy}',
        received_events_url: 'https://api.github.com/users/Gwillison415/received_events',
        type: 'User',
        site_admin: false,
      },
    ],
    milestone: {
      url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/milestones/1',
      html_url: 'https://github.com/ShareCastG52/Q2_Project/milestone/1',
      labels_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/milestones/1/labels',
      id: 2601714,
      number: 1,
      title: 'building paths and auth',
      description: null,
      creator: {
        login: 'Gwillison415',
        id: 22106099,
        avatar_url: 'https://avatars2.githubusercontent.com/u/22106099?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/Gwillison415',
        html_url: 'https://github.com/Gwillison415',
        followers_url: 'https://api.github.com/users/Gwillison415/followers',
        following_url: 'https://api.github.com/users/Gwillison415/following{/other_user}',
        gists_url: 'https://api.github.com/users/Gwillison415/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/Gwillison415/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/Gwillison415/subscriptions',
        organizations_url: 'https://api.github.com/users/Gwillison415/orgs',
        repos_url: 'https://api.github.com/users/Gwillison415/repos',
        events_url: 'https://api.github.com/users/Gwillison415/events{/privacy}',
        received_events_url: 'https://api.github.com/users/Gwillison415/received_events',
        type: 'User',
        site_admin: false,
      },
      open_issues: 3,
      closed_issues: 0,
      state: 'open',
      created_at: '2017-06-23T22:45:34Z',
      updated_at: '2017-07-31T20:22:10Z',
      due_on: null,
      closed_at: null,
    },
    comments: 0,
    created_at: '2017-06-27T17:23:16Z',
    updated_at: '2017-07-31T20:22:10Z',
    closed_at: null,
    body: 'Create functionality to delete users in routes/login.js OR routes/register.js',
  },
  {
    url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/16',
    repository_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project',
    labels_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/16/labels{/name}',
    comments_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/16/comments',
    events_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/16/events',
    html_url: 'https://github.com/ShareCastG52/Q2_Project/issues/16',
    id: 238923429,
    number: 16,
    title: 'login test JWT token',
    user: {
      login: 'Gwillison415',
      id: 22106099,
      avatar_url: 'https://avatars2.githubusercontent.com/u/22106099?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Gwillison415',
      html_url: 'https://github.com/Gwillison415',
      followers_url: 'https://api.github.com/users/Gwillison415/followers',
      following_url: 'https://api.github.com/users/Gwillison415/following{/other_user}',
      gists_url: 'https://api.github.com/users/Gwillison415/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Gwillison415/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Gwillison415/subscriptions',
      organizations_url: 'https://api.github.com/users/Gwillison415/orgs',
      repos_url: 'https://api.github.com/users/Gwillison415/repos',
      events_url: 'https://api.github.com/users/Gwillison415/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Gwillison415/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 632975276,
        url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/labels/duplicate',
        name: 'duplicate',
        color: 'cccccc',
        default: true,
      },
      {
        id: 632975278,
        url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/labels/help%20wanted',
        name: 'help wanted',
        color: '128A0C',
        default: true,
      },
      {
        id: 632975280,
        url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/labels/question',
        name: 'question',
        color: 'cc317c',
        default: true,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: {
      url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/milestones/1',
      html_url: 'https://github.com/ShareCastG52/Q2_Project/milestone/1',
      labels_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/milestones/1/labels',
      id: 2601714,
      number: 1,
      title: 'building paths and auth',
      description: null,
      creator: {
        login: 'Gwillison415',
        id: 22106099,
        avatar_url: 'https://avatars2.githubusercontent.com/u/22106099?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/Gwillison415',
        html_url: 'https://github.com/Gwillison415',
        followers_url: 'https://api.github.com/users/Gwillison415/followers',
        following_url: 'https://api.github.com/users/Gwillison415/following{/other_user}',
        gists_url: 'https://api.github.com/users/Gwillison415/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/Gwillison415/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/Gwillison415/subscriptions',
        organizations_url: 'https://api.github.com/users/Gwillison415/orgs',
        repos_url: 'https://api.github.com/users/Gwillison415/repos',
        events_url: 'https://api.github.com/users/Gwillison415/events{/privacy}',
        received_events_url: 'https://api.github.com/users/Gwillison415/received_events',
        type: 'User',
        site_admin: false,
      },
      open_issues: 3,
      closed_issues: 0,
      state: 'open',
      created_at: '2017-06-23T22:45:34Z',
      updated_at: '2017-07-31T20:22:10Z',
      due_on: null,
      closed_at: null,
    },
    comments: 0,
    created_at: '2017-06-27T17:20:27Z',
    updated_at: '2017-07-31T20:21:31Z',
    closed_at: null,
    body: "shouldn't have regex should have actual token to test against for better test coverage ",
  },
  {
    url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/10',
    repository_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project',
    labels_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/10/labels{/name}',
    comments_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/10/comments',
    events_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/10/events',
    html_url: 'https://github.com/ShareCastG52/Q2_Project/issues/10',
    id: 238437817,
    number: 10,
    title: 'search queries seem to only return XML ',
    user: {
      login: 'Gwillison415',
      id: 22106099,
      avatar_url: 'https://avatars2.githubusercontent.com/u/22106099?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Gwillison415',
      html_url: 'https://github.com/Gwillison415',
      followers_url: 'https://api.github.com/users/Gwillison415/followers',
      following_url: 'https://api.github.com/users/Gwillison415/following{/other_user}',
      gists_url: 'https://api.github.com/users/Gwillison415/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Gwillison415/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Gwillison415/subscriptions',
      organizations_url: 'https://api.github.com/users/Gwillison415/orgs',
      repos_url: 'https://api.github.com/users/Gwillison415/repos',
      events_url: 'https://api.github.com/users/Gwillison415/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Gwillison415/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2017-06-26T04:13:23Z',
    updated_at: '2017-06-26T04:13:23Z',
    closed_at: null,
    body: 'a search like https://gpodder.net/search/?q=bbc+news returns XML\r\n\r\nwe may need to learn how to handle that format to return / translate relevant results\r\n',
  },
  {
    url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/9',
    repository_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project',
    labels_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/9/labels{/name}',
    comments_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/9/comments',
    events_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/9/events',
    html_url: 'https://github.com/ShareCastG52/Q2_Project/issues/9',
    id: 238436159,
    number: 9,
    title: 'client parameterization',
    user: {
      login: 'Gwillison415',
      id: 22106099,
      avatar_url: 'https://avatars2.githubusercontent.com/u/22106099?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Gwillison415',
      html_url: 'https://github.com/Gwillison415',
      followers_url: 'https://api.github.com/users/Gwillison415/followers',
      following_url: 'https://api.github.com/users/Gwillison415/following{/other_user}',
      gists_url: 'https://api.github.com/users/Gwillison415/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Gwillison415/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Gwillison415/subscriptions',
      organizations_url: 'https://api.github.com/users/Gwillison415/orgs',
      repos_url: 'https://api.github.com/users/Gwillison415/repos',
      events_url: 'https://api.github.com/users/Gwillison415/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Gwillison415/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: '2017-06-26T03:54:45Z',
    updated_at: '2017-06-26T06:39:55Z',
    closed_at: null,
    body: "not sure if/how this plays a role but something tells me it's holding up API calls \r\nhttp://gpoddernet.readthedocs.io/en/latest/api/reference/clientconfig.html",
  },
  {
    url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/8',
    repository_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project',
    labels_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/8/labels{/name}',
    comments_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/8/comments',
    events_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/8/events',
    html_url: 'https://github.com/ShareCastG52/Q2_Project/issues/8',
    id: 238413720,
    number: 8,
    title: 'Create podcasts and episodes routes',
    user: {
      login: 'meghanprestemon',
      id: 24230076,
      avatar_url: 'https://avatars1.githubusercontent.com/u/24230076?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/meghanprestemon',
      html_url: 'https://github.com/meghanprestemon',
      followers_url: 'https://api.github.com/users/meghanprestemon/followers',
      following_url: 'https://api.github.com/users/meghanprestemon/following{/other_user}',
      gists_url: 'https://api.github.com/users/meghanprestemon/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/meghanprestemon/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/meghanprestemon/subscriptions',
      organizations_url: 'https://api.github.com/users/meghanprestemon/orgs',
      repos_url: 'https://api.github.com/users/meghanprestemon/repos',
      events_url: 'https://api.github.com/users/meghanprestemon/events{/privacy}',
      received_events_url: 'https://api.github.com/users/meghanprestemon/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2017-06-25T23:17:12Z',
    updated_at: '2017-06-25T23:17:12Z',
    closed_at: null,
    body: "I think people will need to be able to search through podcasts and episodes so we'll have to make routes for them to query by genre, artist, etc.",
  },
  {
    url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/7',
    repository_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project',
    labels_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/7/labels{/name}',
    comments_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/7/comments',
    events_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/7/events',
    html_url: 'https://github.com/ShareCastG52/Q2_Project/issues/7',
    id: 238333863,
    number: 7,
    title: 'ask about test',
    user: {
      login: 'Gwillison415',
      id: 22106099,
      avatar_url: 'https://avatars2.githubusercontent.com/u/22106099?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Gwillison415',
      html_url: 'https://github.com/Gwillison415',
      followers_url: 'https://api.github.com/users/Gwillison415/followers',
      following_url: 'https://api.github.com/users/Gwillison415/following{/other_user}',
      gists_url: 'https://api.github.com/users/Gwillison415/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Gwillison415/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Gwillison415/subscriptions',
      organizations_url: 'https://api.github.com/users/Gwillison415/orgs',
      repos_url: 'https://api.github.com/users/Gwillison415/repos',
      events_url: 'https://api.github.com/users/Gwillison415/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Gwillison415/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 632975280,
        url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/labels/question',
        name: 'question',
        color: 'cc317c',
        default: true,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: {
      url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/milestones/2',
      html_url: 'https://github.com/ShareCastG52/Q2_Project/milestone/2',
      labels_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/milestones/2/labels',
      id: 2672293,
      number: 2,
      title: 'test milestone',
      description: null,
      creator: {
        login: 'Gwillison415',
        id: 22106099,
        avatar_url: 'https://avatars2.githubusercontent.com/u/22106099?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/Gwillison415',
        html_url: 'https://github.com/Gwillison415',
        followers_url: 'https://api.github.com/users/Gwillison415/followers',
        following_url: 'https://api.github.com/users/Gwillison415/following{/other_user}',
        gists_url: 'https://api.github.com/users/Gwillison415/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/Gwillison415/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/Gwillison415/subscriptions',
        organizations_url: 'https://api.github.com/users/Gwillison415/orgs',
        repos_url: 'https://api.github.com/users/Gwillison415/repos',
        events_url: 'https://api.github.com/users/Gwillison415/events{/privacy}',
        received_events_url: 'https://api.github.com/users/Gwillison415/received_events',
        type: 'User',
        site_admin: false,
      },
      open_issues: 1,
      closed_issues: 0,
      state: 'open',
      created_at: '2017-07-31T20:25:51Z',
      updated_at: '2017-07-31T20:25:51Z',
      due_on: null,
      closed_at: null,
    },
    comments: 0,
    created_at: '2017-06-24T18:28:23Z',
    updated_at: '2017-07-31T20:25:51Z',
    closed_at: null,
    body: "wasn't able to make a connection to test db and wondering about that\r\n\r\nASK PROF",
  },
  {
    url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/4',
    repository_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project',
    labels_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/4/labels{/name}',
    comments_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/4/comments',
    events_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/4/events',
    html_url: 'https://github.com/ShareCastG52/Q2_Project/issues/4',
    id: 238279668,
    number: 4,
    title: '.index() usefulness (shared)',
    user: {
      login: 'Gwillison415',
      id: 22106099,
      avatar_url: 'https://avatars2.githubusercontent.com/u/22106099?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Gwillison415',
      html_url: 'https://github.com/Gwillison415',
      followers_url: 'https://api.github.com/users/Gwillison415/followers',
      following_url: 'https://api.github.com/users/Gwillison415/following{/other_user}',
      gists_url: 'https://api.github.com/users/Gwillison415/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Gwillison415/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Gwillison415/subscriptions',
      organizations_url: 'https://api.github.com/users/Gwillison415/orgs',
      repos_url: 'https://api.github.com/users/Gwillison415/repos',
      events_url: 'https://api.github.com/users/Gwillison415/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Gwillison415/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2017-06-24T00:11:39Z',
    updated_at: '2017-06-24T00:11:39Z',
    closed_at: null,
    body: 'https://www.postgresql.org/docs/9.1/static/sql-createindex.html\r\n\r\nspeeds it up until it does not.. whats up with that? \r\n\r\nASK TEACHER',
  },
  {
    url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/3',
    repository_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project',
    labels_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/3/labels{/name}',
    comments_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/3/comments',
    events_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/3/events',
    html_url: 'https://github.com/ShareCastG52/Q2_Project/issues/3',
    id: 238279390,
    number: 3,
    title: 'postgres dB CASCADE on delete design change',
    user: {
      login: 'Gwillison415',
      id: 22106099,
      avatar_url: 'https://avatars2.githubusercontent.com/u/22106099?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Gwillison415',
      html_url: 'https://github.com/Gwillison415',
      followers_url: 'https://api.github.com/users/Gwillison415/followers',
      following_url: 'https://api.github.com/users/Gwillison415/following{/other_user}',
      gists_url: 'https://api.github.com/users/Gwillison415/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Gwillison415/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Gwillison415/subscriptions',
      organizations_url: 'https://api.github.com/users/Gwillison415/orgs',
      repos_url: 'https://api.github.com/users/Gwillison415/repos',
      events_url: 'https://api.github.com/users/Gwillison415/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Gwillison415/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2017-06-24T00:08:41Z',
    updated_at: '2017-06-24T00:08:41Z',
    closed_at: null,
    body: 'fky to users table and favorites table cascade on delete or isActive flag creating a partition on active views    https://stackoverflow.com/questions/102278/active-flag-or-not',
  },
  {
    url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/2',
    repository_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project',
    labels_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/2/labels{/name}',
    comments_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/2/comments',
    events_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/issues/2/events',
    html_url: 'https://github.com/ShareCastG52/Q2_Project/issues/2',
    id: 238269960,
    number: 2,
    title: 'we may need a token route',
    user: {
      login: 'Gwillison415',
      id: 22106099,
      avatar_url: 'https://avatars2.githubusercontent.com/u/22106099?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Gwillison415',
      html_url: 'https://github.com/Gwillison415',
      followers_url: 'https://api.github.com/users/Gwillison415/followers',
      following_url: 'https://api.github.com/users/Gwillison415/following{/other_user}',
      gists_url: 'https://api.github.com/users/Gwillison415/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Gwillison415/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Gwillison415/subscriptions',
      organizations_url: 'https://api.github.com/users/Gwillison415/orgs',
      repos_url: 'https://api.github.com/users/Gwillison415/repos',
      events_url: 'https://api.github.com/users/Gwillison415/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Gwillison415/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: {
      url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/milestones/1',
      html_url: 'https://github.com/ShareCastG52/Q2_Project/milestone/1',
      labels_url: 'https://api.github.com/repos/ShareCastG52/Q2_Project/milestones/1/labels',
      id: 2601714,
      number: 1,
      title: 'building paths and auth',
      description: null,
      creator: {
        login: 'Gwillison415',
        id: 22106099,
        avatar_url: 'https://avatars2.githubusercontent.com/u/22106099?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/Gwillison415',
        html_url: 'https://github.com/Gwillison415',
        followers_url: 'https://api.github.com/users/Gwillison415/followers',
        following_url: 'https://api.github.com/users/Gwillison415/following{/other_user}',
        gists_url: 'https://api.github.com/users/Gwillison415/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/Gwillison415/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/Gwillison415/subscriptions',
        organizations_url: 'https://api.github.com/users/Gwillison415/orgs',
        repos_url: 'https://api.github.com/users/Gwillison415/repos',
        events_url: 'https://api.github.com/users/Gwillison415/events{/privacy}',
        received_events_url: 'https://api.github.com/users/Gwillison415/received_events',
        type: 'User',
        site_admin: false,
      },
      open_issues: 3,
      closed_issues: 0,
      state: 'open',
      created_at: '2017-06-23T22:45:34Z',
      updated_at: '2017-07-31T20:22:10Z',
      due_on: null,
      closed_at: null,
    },
    comments: 0,
    created_at: '2017-06-23T22:45:22Z',
    updated_at: '2017-06-23T22:45:34Z',
    closed_at: null,
    body: "i think that we're asking our users route do 'to do too much'\r\ni could be wrong but basically i'm building the auth into users and set-cookie there and that means either we tweak users route to also have get methods or we build a token route as well... hmmmmm",
  },
];
// function findAssignee(data) {
//   return data.map(issue => issue.assignees.forEach(assignee => assignee));
// }

export default issuesMock;
