export const milestoneMock = [
  {
    "url": "https://api.github.com/repos/ShareCastG52/Q2_Project/milestones/2",
    "html_url": "https://github.com/ShareCastG52/Q2_Project/milestone/2",
    "labels_url": "https://api.github.com/repos/ShareCastG52/Q2_Project/milestones/2/labels",
    "id": 2672293,
    "number": 2,
    "title": "test milestone",
    "description": null,
    "creator": {
      "login": "Gwillison415",
      "id": 22106099,
      "avatar_url": "https://avatars2.githubusercontent.com/u/22106099?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Gwillison415",
      "html_url": "https://github.com/Gwillison415",
      "followers_url": "https://api.github.com/users/Gwillison415/followers",
      "following_url": "https://api.github.com/users/Gwillison415/following{/other_user}",
      "gists_url": "https://api.github.com/users/Gwillison415/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Gwillison415/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Gwillison415/subscriptions",
      "organizations_url": "https://api.github.com/users/Gwillison415/orgs",
      "repos_url": "https://api.github.com/users/Gwillison415/repos",
      "events_url": "https://api.github.com/users/Gwillison415/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Gwillison415/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 1,
    "closed_issues": 0,
    "state": "open",
    "created_at": "2017-07-31T20:25:51Z",
    "updated_at": "2017-07-31T20:25:51Z",
    "due_on": null,
    "closed_at": null
  },
  {
    "url": "https://api.github.com/repos/ShareCastG52/Q2_Project/milestones/1",
    "html_url": "https://github.com/ShareCastG52/Q2_Project/milestone/1",
    "labels_url": "https://api.github.com/repos/ShareCastG52/Q2_Project/milestones/1/labels",
    "id": 2601714,
    "number": 1,
    "title": "building paths and auth",
    "description": null,
    "creator": {
      "login": "Gwillison415",
      "id": 22106099,
      "avatar_url": "https://avatars2.githubusercontent.com/u/22106099?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Gwillison415",
      "html_url": "https://github.com/Gwillison415",
      "followers_url": "https://api.github.com/users/Gwillison415/followers",
      "following_url": "https://api.github.com/users/Gwillison415/following{/other_user}",
      "gists_url": "https://api.github.com/users/Gwillison415/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Gwillison415/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Gwillison415/subscriptions",
      "organizations_url": "https://api.github.com/users/Gwillison415/orgs",
      "repos_url": "https://api.github.com/users/Gwillison415/repos",
      "events_url": "https://api.github.com/users/Gwillison415/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Gwillison415/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 3,
    "closed_issues": 0,
    "state": "open",
    "created_at": "2017-06-23T22:45:34Z",
    "updated_at": "2017-07-31T20:22:10Z",
    "due_on": null,
    "closed_at": null
  }
]
